name: Ateex Auto Earn

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav/latvi
          token: ${{ secrets.REPO_PAT }}
          ref: main

      - uses: alphaxcv/warp@1.0

      - run: bash test.sh
        env:
          ATEEX_EMAIL: ${{ secrets.ATEEX_EMAIL }}
          ATEEX_PASSWORD: ${{ secrets.ATEEX_PASSWORD }}

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: runtime-screenshot
          path: "*.png"
