name: Bot-hosting earn Coin

on:

  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav1/bothosting
          token: ${{ secrets.REPO_PAT }}
          ref: main
          
      - uses: alphaxcv/warp@1.0
      
      - run: bash run.sh
        env:
          SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
          REPO_PAT: ${{ secrets.REPO_PAT }}
          
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"
