name: FalixNodes Auto Restart

on:

  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav1/falixnodes
          token: ${{ secrets.REPO_PAT }}
          ref: main

      - uses: alphaxcv/warp-on-actions@1.0
        with:
          stack: dual
          mode: wireguard

      - run: bash run.sh
        env:
          FALIX_EMAIL: ${{ secrets.FALIX_EMAIL }}
          FALIX_PASSWORD: ${{ secrets.FALIX_PASSWORD }}

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: falixnodes-debug-screenshots
          path: "*.png"
