name: FreeMCHosting Reward

on:
  schedule:
    - cron: '19 23 * * *'
  workflow_dispatch:

jobs:
  reward:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav1/freemchosting
          token: ${{ secrets.REPO_PAT }}
          ref: main

      - uses: alphaxcv/warp@1.0

      - run: bash run.sh
        env:
          FREEMCHOSTING_ACCOUNTS: ${{ secrets.FREEMCHOSTING_ACCOUNTS }}

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: runtime-debug-files
          path: |
            *.png
            *.log
          if-no-files-found: ignore
