name: FreezeHost Renew

on:
  schedule:
    - cron: '13 20 * * *'
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav1/freezehost
          token: ${{ secrets.REPO_PAT }}
          ref: main

      - uses: alphaxcv/warp-on-actions@1.0
        with:
          stack: dual
          mode: wireguard

      - run: bash run.sh
        env:
          DISCORD_EMAIL: ${{ secrets.DISCORD_EMAIL }}
          DISCORD_PASSWORD: ${{ secrets.DISCORD_PASSWORD }}
          SOCKS5_PROXY: ${{ secrets.SOCKS5_PROXY }}

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: runtime-artifacts
          path: "*.png"
          if-no-files-found: ignore
