name: G4F Auto Renew

on:
  workflow_dispatch: # 允许手动触发

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: seav1/gaming4free
          token: ${{ secrets.REPO_PAT }}
          ref: main

      - uses: alphaxcv/warpx@1.0
          
      - name: Execute Run Script
        run: bash run.sh
        env:
          SERVER_NAMES: ${{ secrets.SERVER_NAMES }} 

      - name: Upload Debug Screenshot (Only on Failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "*.png"
