name: Hnhost Login

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav1/hnhost
          token: ${{ secrets.REPO_PAT }}
          ref: main

      - name: HY2
        env:
          HY2_LINK: ${{ secrets.HY2_LINK_DISCORD }}
        run: |
          wget -qO hy2 https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-amd64 && chmod +x hy2
          printf "server: $HY2_LINK\nsocks5:\n  listen: 127.0.0.1:1080" > c.yaml
          ./hy2 client -c c.yaml > /dev/null 2>&1 &
          timeout 30s sh -c 'until nc -z 127.0.0.1 1080; do sleep 1; done' || (echo "time out" && exit 1)
          
      - run: bash run.sh
        env:
          DISCORD_EMAIL: ${{ secrets.DISCORD_EMAIL }}
          DISCORD_PASSWORD: ${{ secrets.DISCORD_PASSWORD }}
          HNHOST_SERVER_IDS: ${{ secrets.HNHOST_SERVER_IDS }}

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"
