name: Host2Play Auto Renew

on:
  workflow_dispatch:

jobs:
  renew_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav1/host2play
          token: ${{ secrets.REPO_PAT }}
          ref: main
          
      - uses: alphaxcv/warp-on-actions@1.0
        with:
          stack: dual
          mode: wireguard
          
      - run: bash run.sh

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          retention-days: 1
          path: "*.png"
