name: host2play

on:
  schedule:
    - cron: '3 */6 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone private repo and run
        env:
          REPO_PAT: ${{ secrets.REPO_PAT }}
        run: |
          git clone https://x-access-token:${REPO_PAT}@github.com/seav1/host2play-private.git private
          cd private
          chmod +x run.sh
          ./run.sh
