name: Host2Play Auto Renew 1

on:
  schedule:
    - cron: '13 */3 * * *'
  workflow_dispatch:
  
jobs:
  renew_bot:
    name: 执行续期脚本
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav1/host2play1
          token: ${{ secrets.REPO_PAT }}
          ref: main
          fetch-depth: 0

      - uses: alphaxcv/warpx@1.0

      - run: bash run.sh

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          retention-days: 1
          path: output/screenshots/*.png
