name: Pingless Renew
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav1/pingless
          token: ${{ secrets.REPO_PAT }}
          ref: main

      - run: bash run.sh
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKENA }}

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"
          if-no-files-found: ignore
