name: Teoheberg Auto Earn

on:
  workflow_dispatch:
  schedule:
    - cron: "17 13 * * *"
  
jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
        with:
          repository: seav1/teoheberg
          token: ${{ secrets.REPO_PAT }}
          ref: main


      - name: Setup proxy
        id: proxy
        uses: alphaxcv/proxy_sb@1.0
        with:
          node_link: ${{ secrets.NODE_LINK }}

      - run: bash run.sh
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: runtime-output
          path: |
            *.png
            *.log
          if-no-files-found: ignore
